### ISSUE TITLE
[Feat] npm 배포하기 위한 작업들

### ISSUE THREAD

**Issue by kimdw524** [Memory-Orgel/OYCDesignSystem#13]
## 📔 Description

프로젝트에서 사용할 수 있도록 npm에 배포하기 위한 작업들

## 🐈 Todo

- [x] 컴포넌트 타입 정의 (d.ts)
- [x] package.json 수정
- [x] babel config
- [x] README.md 작성
